### ISSUE TITLE
Export encountered errors on following paths: /gallery

### ISSUE THREAD

**Issue by masapasa** [zpuckeridge/blog#81]
Hi @zpuckeridge , Is this error coming from cloudflare api? Can you please post env example with all the api key variables. Thank you so much!

npm run build

> next-blog@0.1.0 build
> next build

info  - Loaded env from /Usersblog/.env.local
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[    ] info  - Generating static pages (0/48)
Error occurred prerendering page "/gallery". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of null (reading 'images')
    at getStaticProps (/Usersblog/.next/server/pages/gallery.js:213:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async renderToHTML (/Usersblog/node_modules/next/dist/server/render.js:385:20)
    at async /Usersblog/node_modules/next/dist/export/worker.js:277:36
    at async Span.traceAsyncFn (/Usersblog/node_modules/next/dist/trace/trace.js:79:20)
info  - Generating static pages (48/48)

> Build error occurred
Error: Export encountered errors on following paths:
        /gallery
    at /Usersblog/node_modules/next/dist/export/index.js:409:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (/Usersblog/node_modules/next/dist/trace/trace.js:79:20)
    at async /Usersblog/node_modules/next/dist/build/index.js:1345:21
    at async Span.traceAsyncFn (/Usersblog/node_modules/next/dist/trace/trace.js:79:20)
    at async /Usersblog/node_modules/next/dist/build/index.js:1205:17
    at async Span.traceAsyncFn (/Usersblog/node_modules/next/dist/trace/trace.js:79:20)
    at async Object.build [as default] (/Usersblog/node_modules/next/dist/build/index.js:66:29)

**Comment by zpuckeridge** [comment]
Hi @masapasa! :wave: 

I've gone ahead and added those environment variables now in 1b11acc7d68513727d4ab4ec828a47315047bd52
